### PR TITLE
Fixed previous enhancements to `numeric_between`

### PR DESCRIPTION
**Pull request by maoueh**
Messages have been updated as well as testing invalid argument panic on `numeric_between` rule.

### CODE REVIEW

**Comment by maoueh** [comment]
@thedevsaddam Can you merge this one, messages are all fucked up right now if you left out one of the bound.

**Comment by thedevsaddam** [comment]
@maoueh Can you please fix the error. `httptest.NewRequest` wasn't before 1.6, use build tag or do something else to fix this.

**Comment by maoueh** [comment]
Sure no problem, I’ll fix this using JSON instead of request.

**Comment by thedevsaddam** [comment]
@maoueh Any update for the issue?

**Comment by maoueh** [comment]
@thedevsaddam Build passes now, should be good to merge.

**Pull request merged**
